apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: scenescape-git-repo
  namespace: scenescape
spec:
  interval: 10m
  url: https://github.com/harishb93/scenescape
  ref:
    branch: 1.4.0-alpha